[webservers]
web-1 ansible_host=51.250.84.103 fqdn=fhm70s9k0bgulsoic0bo.auto.internal
web-2 ansible_host=158.160.50.225 fqdn=fhmuc5cs9jd02lat58b4.auto.internal

[databases]
main ansible_host=84.201.156.101 fqdn=fhmgo84rpvb67jgnnsil.auto.internal
replica ansible_host=51.250.9.57 fqdn=fhmnitle7nerfct8opnv.auto.internal

[storage]
storage ansible_host=130.193.51.221 fqdn=fhm506ptu99bpdf9g75u.auto.internal
